### ISSUE TITLE
Test smartbanner on Android

### ISSUE THREAD

**Issue by emerencia** [roqua/leefplezier_app#1]
It works on iOS, does the smartbanner work under android? Only one person can find out.

**Comment by frbl** [comment]
![mpamc_screenshot_2015-03-03-11-34-04](https://cloud.githubusercontent.com/assets/617574/6460699/b8ea1e7a-c199-11e4-85de-6e2fa155d807.png)

**Comment by frbl** [comment]
Knop point wel naar nu.nl

**Comment by emerencia** [comment]
Fixed.
